platform :ios do
  before_all do
  	# pod install
    sh 'pod install'
  end

  desc "打包测试包"
  lane :developer do
  	scheme_name = "RKIM-Example"
    xcodeproj = "RKIM.xcodeproj"
    version = get_version_number(
                  xcodeproj:xcodeproj,
                  target: "RKIM"
    )
    build_app(workspace: "RKIM.xcworkspace", scheme: scheme_name, export_method: "development")
     pgyer(api_key: "dfaf99096c704f8340279997893b1781",
     			 user_key: "95cd9337213e2e1f96704e6a4a7aae92", 
     			 password: "123456", 
     			 install_type: "2")
     # 钉钉发出提醒
    sh "./dingding.sh " +  version
  end


  # You can define as many lanes as you want

  after_all do |lane|

  end

  error do |lane, exception|
    # slack(
    #   message: "Error message"
    # )
  end
end