
use_frameworks!
source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

platform :ios, '10.0'

def gitUrl (name)
   url = 'https://github.com/RokidiOS/'
   return url + name
end

target 'RKIM_Example' do
  pod 'RKIM', :path => '../'
  pod 'RKILogger', '0.2.5'
  pod 'RKIBaseView', :git => gitUrl("RKBaseView")
  pod 'RKIUtils'
  pod 'RKIHandyJSON'
  pod 'RKIMCore',  :path => "../../RKIMCore"
#pod 'RKIMCore', :git => gitUrl("RKIMCore"), :branch => "0.1.2_swift5.5.2"
#  pod 'RKIMCore', :path => "/Users/chzy/Desktop/Rokid/custom/RKIMCore/Framework"
#  gitUrl("RKIMCore")
  
  
  pod 'LookinServer', :configurations => ['Debug']
  pod 'DoraemonKit'
  pod 'RKSocket', :git => gitUrl("RKSocket")
  pod 'Moya', '~> 15.0.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
#      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "iOS 10.0"
    end
  end
end
