
use_frameworks!
source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

platform :ios, '9.0'

url = 'https://github.com/RokidiOS/'

target 'RKIM_Example' do
  pod 'RKIM', :path => '../'
  pod 'RKILogger', :git => url + "RKLogger"
  pod 'RKIBaseView', :git => url + "RKBaseView"
  pod 'RKIUtils', :git => url + "RKUtils"
  pod 'RKIHandyJSON', :git => url +'RKHandyJSON'
  pod 'RKIMCore', :git => url + "RKIMCore"
  pod 'LookinServer', :configurations => ['Debug']
  pod 'DoraemonKit'
 
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
