
use_frameworks!
source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

platform :ios, '10.0'

def gitUrl (name)
   url = 'https://github.com/RokidiOS/'
   return url + name
end

target 'RKIM_Example' do
  pod 'RKIM', :path => '../'
  pod 'RKILogger'
  pod 'RKIBaseView', :git => gitUrl("RKBaseView")
  pod 'RKIUtils'
  pod 'RKIHandyJSON'
  pod 'RKIMCore',  :git => gitUrl("RKIMCore")
  
  
  pod 'LookinServer', :configurations => ['Debug']
  pod 'DoraemonKit'
  pod 'RKSocket', :git => gitUrl("RKSocket")
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
